Container_Properties:
  Fedora_Version: "43"
  SSH_Key_Location: "~/.ssh/github_id"
  Fedora_Remix_Location: "/home/travis/Remix_Builder"
  GitHub_Registry_Owner: "tmichett"
  Image_Name: "ghcr.io/tmichett/fedora-remix-builder:43"

